### ISSUE TITLE
nonClinicalRPC Locker like VPRLocker

### ISSUE THREAD

**Issue by conorcaregraf** [vistadataproject/nonClinicalRPCs#1]
__Background__: non clinical RPCs address meta data - for example, drug definitions, problem types, orderable items - that drive the system. CPRS uses RPCs to access this data, some of which is standard across the VA, some local to a particular system.

__TODO__: modeled on the VPR Locker, establish a __kLocker_ that locks the META RPCs over VDM and simple service wrappers like the Parameter Service

__Easiest RPCs__: _handlebars over file(s)_, parameter get calls over a parameter service wrapper

**Comment by mfuroyama** [comment]
For now, I set up a directory structure for prototyped non-clinical RPC locker models modeled after the VDM `prototypes` directory structure.  `require`-ing the `nonClinicalRPCs/prototypes` module gives you:

* `rpcLModel` (RPC Locker Models)
* `vdmModel` (Non-Clinical VDM Model)

**Comment by mfuroyama** [comment]
Putting this on hold until the new Facade/Locker architecture is rolled out, since this will depend on the new implementation structure.

**Comment by mfuroyama** [comment]
New architectural changes made to nodeVISTA and VDM accomplish this task.  There is now a new NonClinical Locker class in VDM that supports this issue.
