### ISSUE TITLE
In NC RPCs, a/c for all Robert Alexander Parameter settings in demo nodeVISTA

### ISSUE THREAD

**Issue by conorcaregraf** [vistadataproject/nonClinicalRPCs#118]
![screen shot 2017-03-16 at 12 30 32 pm](https://cloud.githubusercontent.com/assets/1831390/24015055/7730b890-0a44-11e7-8585-d3d94ef73463.png)

in 8995_5 ([query](http://localhost:9000/query?fmql=SELECT%208989_5&format=HTML))

?: Use Parameter Utilities' _GET PARAMETER VALUE FOR A USER_ call to grab all Robert's values and then trace back how they get set.

__Background__: want to eventually start with an empty 8995 in nodeVISTA and populate [1] explicitly in setup and [2] know why CPRS activity populates it and make sure all that population is through locked RPCs.

**Comment by mfuroyama** [comment]
Moved to Jira, addressed in VAM-151
