### ISSUE TITLE
Update Demo Screenshots in the VDP Public Website

### ISSUE THREAD

**Issue by mfuroyama** [vistadataproject/nonClinicalRPCs#156]
With all the updates to the NodeVISTA Manager (formerly known as the MVDM Manager) UI, some of the images and text in the VDP public website demo page (http://vistadataproject.info/demo/) have become outdated.  We need to capture fresh screenshots (and update any outdated text) within the various captured domains:

* [x] [Allergies](http://vistadataproject.info/demo/Allergies)
    Assigned to: Adam
* [x] [Problems](http://vistadataproject.info/demo/Problems)
    Assigned to: Sid
* [x] [Vitals](http://vistadataproject.info/demo/Vitals)
    Assigned to: Adam

Here's the Github repo link for the website page: https://github.com/vistadataproject/vistadataproject.github.io

Demo images are here:
https://github.com/vistadataproject/vistadataproject.github.io/tree/master/demo/images

**Comment by mfuroyama** [comment]
Mentioning @sbruno81 and @conorcaregraf as an FYI that we're, in fact, working on these...

**Comment by sidjtd** [comment]
I'll hit up the Problems....

**Comment by kekuso** [comment]
my allergies are telling me to work on Allergies
