### ISSUE TITLE
VDM-based User Testing

### ISSUE THREAD

**Issue by conorcaregraf** [vistadataproject/nonClinicalRPCs#159]
Moved from nodeVISTA/setup to prototype/user

First priority: ensure VDM based creation is the same as Python-driven creation in nodeVISTA/setup. Expect VDM.describe of results to be the same.

Second: are there indexes beyond FileMan being setup in the Python (roll and scroll) that will need to be added above VDM based loading?

Review: Steve's Patient tests in vdm/patient. There are updates for PATIENT (2) and tests for read RPCs

Clone work related: need to test assumptions about Users against the data in the clone.

**Comment by conorcaregraf** [comment]
Some background ...

> For every doctor, there are 16 other health care workers. And half of those 16 are in administrative and other nonclinical roles, according to Bob Kocher, a former Obama administration official who worked on the Affordable Care Act and is now a partner in the venture capital firm Venrock.

so not all workers are docs or nurses (as we know).

__We want__ to put users into __buckets__ but (as KD saw) some of the designations for users in file 2 are inaccurate or partial.

__TODO__: take typical clinical data like Orders (100) or Prescription (52) and isolate users of different types using their type fields. Exs/
  * _ pharmacist_ in 52/Prescriptions ie/ used to identify Pharmacists 
  * provider in _current agent provider_ of file 100 (Orders) ... should be full doctors or at least nurse practitioners
  * attending physican or signed_by in document 8925 (normally clerks can't sign notes)
  * for all data processed (100, 52, 8925), isolate all references to a user (file 200) ie/ get full list of "involved users"

So four buckets:
  1. provider
  2. pharmacist
  3. other (other users not covered in provider or pharmacist)
  4. file 200 entries not in 1/2 or 3

__DO on Psych subset ie/ /data/veteransHospital/psych_, the same data being analyzed by Steve for PATIENT.__ Steve is also making "buckets"

Once you have these buckets, you can then further refine into types of doctor and typical pharmacists etc.

**Comment by mfuroyama** [comment]
I'm pretty sure this evolved into something which was already addressed. Closing...
