### ISSUE TITLE
Parameter Service Interface in Javascript

### ISSUE THREAD

**Issue by conorcaregraf** [vistadataproject/nonClinicalRPCs#2]
__Background__: many non clinical RPCs (ones related to USER in particular) read and write PARAMETER values. VISTA has a MUMPS interface for this. This interface needs to be wrapped in Javascript to allow PARAMETER accessing RPC Lock code to access parameters easily.

MUMPS: 
  * [XPAR.m](https://github.com/OSEHRA/VistA-M/blob/master/Packages/Toolkit/Routines/XPAR.m) - in a nutshell, this MUMPS should become Javascript (which calls db.function MUMPS).
  * some domains like Vitals, wrap this API in their own - [vitals parameter API](http://code.osehra.org/dox/Routine_GMVPAR_source.html)

See VA manual: https://www.va.gov/vdl/documents/Infrastructure/Kernel_Toolkit/ktk7_3p26sp.doc

Note parameters are actually stored in VISTA's DB FileMan - http://localhost:9000/rambler#8989_5 - in effect, a parameter service is a simple overlay with indexing support over the file man representation of parameter settings.

**Comment by conorcaregraf** [comment]
## Some parameter examples (taken from capture.txt after running CPRS)

__ORWDX WRLST__

when you click on the order's tab, CPRS will send this one. The code says it's for "List of dlgs for writing orders" where "digs" mean dialogs. And what it does is, it tells CPRS what options to give in the left panel of its Order tab. And where does this data come from? The parameter "ORWOR WRITE ORDERS LIST". Here's an example of an RPC that returns the values in a parameter, one that would ride over a new parameter service API being called for in issue: https://github.com/vistadataproject/nonClinicalRPCs/issues/2

![screen shot 2017-01-10 at 7 51 36 pm](https://cloud.githubusercontent.com/assets/1831390/21835234/3757d1a6-d770-11e6-9c27-ccc8f3d04732.png)

__ORWCH LOADALL__

this one returns the contents of three parameters which seem to configure CPRS in some way ... the nonClinicalRPC report details them ...

![screen shot 2017-01-10 at 7 47 33 pm](https://cloud.githubusercontent.com/assets/1831390/21835206/07f05a00-d770-11e6-9d60-82f1715fb0a0.png)

... what exactly they set, I don't know but I'm sure we'll find out.

__ORWU USERINFO__

this one counts as "complicated" in a way ... lot's of parameters ABOUT a user. Different users can have different settings - there are per system parameters, global parameters, per user parameters but they all follow the same interface ...

![screen shot 2017-01-10 at 7 50 55 pm](https://cloud.githubusercontent.com/assets/1831390/21835213/118e6f70-d770-11e6-8851-669edaab2c0a.png)

__ORWSR SHOW SURG TAB__

![screen shot 2017-01-10 at 7 55 26 pm](https://cloud.githubusercontent.com/assets/1831390/21835227/242ed552-d770-11e6-8fe1-abde4ee997f4.png)

this is simple. Is one PARAMETER set. But it's not set in nodeVISTA. We will end up setting parameters to effect and enable clinical data development and see new things in CPRS. What happens if we turn this on - do we get a new tab?

**Comment by conorcaregraf** [comment]
## When PARAMETER not used (surprisingly)

some RPCs that ARE NOT parameters but you would think some should be. 

  * XUS INTRO MSG returns the "Hello" message you see when you first bring up CPRS. This message is stored in the intro field of file 8989.3 and not in a parameter. 
  * XWB GET BROKER INFO returns the broker timeout value and it is also stored in 8989.3 and not a parameter.
   * XUS PKI GET UPN also looks into file 200 to see if a user has a PIV card setting. Should that come from 200 or a PARAMETER.? Well, they put it in 200 ...

... so sometimes configurations and settings come from properties of files and there RPCs are file-based even if intuitively you would think they should be in a PARAMETER.

**Comment by conorcaregraf** [comment]
## Current PARAMETER setup in our nodeVISTA install

  * vitals: https://github.com/vistadataproject/nodeVISTA/blob/master/setup/utils/setupVitalsForUsers.js
  * Fix OSEHRA for CAPRI: https://github.com/vistadataproject/nodeVISTA/blob/master/setup/utils/setupCapri.js
  * OSEHRA's setup: https://github.com/vistadataproject/nodeVISTA/blob/master/setup/pySetup/simpleSetup.py (some devolve into PARAMETER setups)

**Comment by conorcaregraf** [comment]
## A/C for types of parameter AND the special parameter lookup index

#### Index

AC defn in DD ...

``` text
^DD(8989.5,.01,1,2,0)="8989.5^AC^MUMPS"
^DD(8989.5,.01,1,2,1)="D S01^XPARDDAC" <---- simply sets up the AC for all file entries
^DD(8989.5,.01,1,2,2)="D K01^XPARDDAC"
^DD(8989.5,.01,1,2,3)="DO NOT DELETE!"
^DD(8989.5,.01,1,2,"%D",0)="^^1^1^2960212^^"
^DD(8989.5,.01,1,2,"%D",1,0)="Multiple filed cross-reference with .02, .03, and 1 fields."
^DD(8989.5,.01,1,2,"DT")=2960207
```

#### Types

![be24d162-8ba2-11e6-8220-0d553649f2fa](https://cloud.githubusercontent.com/assets/1831390/22006310/ea0f3b88-dc1e-11e6-9a2f-a5f7759b268f.png)


``` text
TYPE(X) ; [F] Returns the type of template
 ; Input parameters
 ;  1. X [Literal/Required] Variable pointer to evaluate
 ;
 Q:X="DIC(4.2," 1 ;Domain
 Q:X="DIC(4," 2 ;  Institution
 Q:X="SC(" 3 ;     Hospital Location
 Q:X="VA(200," 4 ; New Person
 Q 0 ;             Unknown
 ; 
```

ie/ __different scopes__ and MOST PARAMETERS are per User (New Person)

More on "ENTITY" as a global moniker (SYS,CLS,BED,DIV)

In ENTDFLT^XPAR1

``` text
 I ENT="SYS" D:'$D(XPARSYS)  S ENT=XPARSYS Q  ; current site
 . S XPARSYS=$$FIND1^DIC(4.2,"","QX",$$KSP^XUPARAM("WHERE"))_";DIC(4.2,"

 ... WHERE Q $P($G(^DIC(4.2,(+^XTV(8989.3,1,0)),0)),"^") ... is where.

 OSEHRA>ZWR ^XTV(8989.3,1,0)
  ^XTV(8989.3,1,0)="87^G.IRM^G.IRM^^0^^1^V" <------ ie. 87 == OSEHRA domain

 I ENT="USR" S ENT=DUZ_";VA(200," Q    ; user in DUZ
 I ENT="CLS" S ENT="" Q                ; no default
 I ENT="TEA" S ENT="" Q                ; no default
 I ENT="BED" S ENT="" Q                ; no default
 I ENT="LOC" S ENT="" Q                ; no default
 I ENT="SRV" S ENT="" Q                ; no default
 I ENT="DIV" D  Q                      ; division in DUZ(2)
 . S ENT="" I +DUZ(2) S ENT=DUZ(2)_";DIC(4,"
 I ENT="PKG" D  Q                      ; package of param namespace
 . N PKG,NAM
 . S NAM=$P(^XTV(8989.51,PAR,0),"^",1),PKG=NAM
 . F  S PKG=$O(^DIC(9.4,"C",PKG),-1) Q:$E(NAM,1,$L(PKG))=PKG
 . S PKG=$O(^DIC(9.4,"C",PKG,0))
 . I PKG S ENT=PKG_";DIC(9.4,"
```

ie/ shorthands for global settings but only USR (DUZ), PKG (from param), SYS (XPARSYS or find from QX of DIC(4.2)

**Comment by conorcaregraf** [comment]
## SYS, USR etc

https://github.com/OSEHRA/VistA-M/blob/master/Packages/Toolkit/Routines/XPAR1.m#L43

is a key piece of code because it translates the "SYS", "USR" etc into entity references. 

Other than checking if entity types are allowed for a parameter, this is the essence of what the interface does. Otherwise, it's just calling a fileman update or lookup on its index.

#### Note on SYS:

```text

  I ENT="SYS" D:'$D(XPARSYS)  S ENT=XPARSYS Q  ; current site

 . S XPARSYS=$$FIND1^DIC(4.2,"","QX",$$KSP^XUPARAM("WHERE"))_";DIC(4.2,"
```

means get from domain setting in Kernel System Parameters (8989_3-1) if XPARSYS not set.

We set domain to 

![screen shot 2017-01-26 at 8 17 41 pm](https://cloud.githubusercontent.com/assets/1831390/22360436/88c75430-e404-11e6-8310-4e0f31ee3b77.png)

**Comment by mfuroyama** [comment]
Note: Code review in VDM (https://github.com/vistadataproject/VDM/pull/184) currently open to address this issue.
