### ISSUE TITLE
Utility RPC: ORWU DT - only partially locked

### ISSUE THREAD

**Issue by conorcaregraf** [vistadataproject/nonClinicalRPCs#3]
ORWU DT has many behaviors. It has only partially been locked which can lead to problems ...

For example, we don't seem to a/c for the case of no arguments or empty [""] arguments and this leads to a popup error in CPRS.

__TODO__: comprehensive tests for all aspects of this RPC and then fully support all behaviors in Javascript.

Note the rpcServer's log/capture.txt shows two variations ...

```text
{
  "name": "ORWU DT",
  "version": "0",
  "args": [
    ""
  ],
  "to": "rpcRunner",
  "rpc": "[XWB]11302\u00010\u0007ORWU DT50000f\u0004",
  "response": "\u0000\u0000-1\u0004",
  "from": "CPRS",
  "timeStamp": "2016-12-22T23:59:34.997Z"
},


{
  "name": "ORWU DT",
  "version": "0",
  "args": [
    "NOW"
  ],
  "to": "rpcRunner",
  "rpc": "[XWB]11302\u00010\u0007ORWU DT50003NOWf\u0004",
  "response": "\u0000\u00003161222.235944\u0004",
  "from": "CPRS",
  "timeStamp": "2016-12-22T23:59:44.912Z"
},
```

currently we only seem to support "NOW".

See implementation to turn to Javascript: https://github.com/OSEHRA/VistA-M/blob/master/Packages/Order%20Entry%20Results%20Reporting/Routines/ORWU.m#L4

**Comment by mfuroyama** [comment]
Hardhats has some pretty good notes on the `%DT` MUMPS routine.

http://www.hardhats.org/fileman/u1/he_intro.htm#date
http://www.hardhats.org/fileman/pm/cl_dt1.htm

According to the documentation it looks like several of the reported formats and option processing pathways are not implemented. Modifying the date/time routines to make it so.
