### ISSUE TITLE
Implement RPCL definitions (Adam)

### ISSUE THREAD

**Issue by sbruno81** [vistadataproject/nonClinicalRPCs#5]
**Implement RPCL definitions for the following RPCs:**

- [x] ORWDX WRLST - naive implementation
- [x] ORWORDG IEN - implemented
- [x] ORWU USERINFO - this one looks complicated...naive implementation
- [x] XUS INTRO MSG - naive implementation. K273 8993.3 link broken or file corrupt
- [x] XUS PKI GET UPN - naive implementation.
- [x] OREVNTX ACTIVE - naive implementation
- [x] ORDDPAPI CLOZMSG - naive implementation
- [x] ORDEA LNKMSG - naive implementation
- [x] ORWPS REASON - naive implementation

See Conor's [session capture](https://github.com/vistadataproject/nonClinicalRPCs/blob/master/conor/capture.txt) and RPC invocation [output](https://github.com/vistadataproject/nonClinicalRPCs/blob/master/conor/ncRPCSimple.output).

**Comment by kekuso** [comment]
@sbruno81 Hey Steve, I finished creating the rpcLModel's, but I've posted a few comments and questions in the first post. Can you please take a look and send me some feedback? Thanks!

**Comment by sbruno81** [comment]
@kekuso

- ORWU USERINFO:

Looks like the error is a mumps dump and we don't have to worry about reproducing mumps dump exceptions. Only tangible responses should be reproduced. For instance, if the routine returned "0" for a bad param, the rpcL implementation should do the same.

- ORWORDG IEN

This routine is a little confusing because of the X param. I looked at Conor's session capture and it looks like a single string parameter is passed to the method. Conor noted that it is an IEN lookup. We should document it like the other IEN lookups. I'd say forget the "X" parameter for now (just notate it) and mark the input parameter as the "display group" since the mumps comment says "	Return IEN for a display group".

**Comment by kekuso** [comment]
@sbruno81 ok thanks Steve!
