### ISSUE TITLE
Short Name vs. Full Name Implementation

### ISSUE THREAD

**Issue by kekuso** [vistadataproject/nonClinicalRPCs#8]
I ran into this issue while implementing the ORWORDG IEN rpc, but this probably applies to multiple rpc's.
ORWORDG IEN accepts both the short name and full names of Display Group items and outputs the corresponding IEN # from this list: http://localhost:9000/rambler#100_98
For example: 
`rpcRunner.run('ORWORDG IEN', ["O RX"])`
and
`rpcRunner.run('ORWORDG IEN', ["OUTPATIENT MEDICATIONS"])`
both return
`4`

This means that there are a total of 112 different cases I need to check (not including errors), not just the 56 that I initially thought I'd need to implement.
There are, of course, several ways to implement this. I chose a brute force method of creating a new JSON object with short names and their matching full names and using vdm.lookupIdByLabel to get the IEN #. (Run `jasmine rpcLTests-ORWORDG_IEN.js` from my directory to see it in action). ~~Note that it only works with the short names right now.~~
Just wanted to get input on if I'm missing something important or if there's a better way to implement the rpcL.

**Comment by mfuroyama** [comment]
Attaching link to RPC for reference:
http://vistadataproject.info/artifacts/vistaRPC%20documentation/ORWORDG%20IEN

**Comment by kekuso** [comment]
Full name or short name args should work now.

**Comment by mfuroyama** [comment]
Hang tight...I might have a solution to this problem that involves some new VDM utilities (currently in code review). Hopefully we won't have to run crazy loops to grab a single IEN!

**Comment by kekuso** [comment]
Great! I think another solution would be to add the short names to VDM.lookupIdByLabel. But if there's a VDM utils method solution that would be even better.

**Comment by mfuroyama** [comment]
@kekuso, actually, I tried a similar approach using first.  I tried creating a `lookupIdByField` function, but it ended up not working.  I'm not sure why, but some of the filtered requests (like "SHORT NAME (3) on 100.98) didn't work.  The utility functions I ended up with seem to be more consistent and generic. I'm probably gonna merge them in later today.  I'll explain the code when I do.

**Comment by mfuroyama** [comment]
Okay, I **just** merged the feature branch in the VDM repo, so if you pull the latest-n-greatest, you should see the changes.

As a note, here's the call syntax for the function:
```Javascript
var result = VDM.lookupIdByCrossReference('Display_Group-100_98', 'B', 'V/M');
```
Note that the function will return a result object on success, or an `Error` object on error.

**Comment by kekuso** [comment]
Sweet, thanks Mike!
