### ISSUE TITLE
Implement File "FILE CHANGE" RPC Locker Definitions: Group 2I

### ISSUE THREAD

**Issue by mfuroyama** [vistadataproject/nonClinicalRPCs#94]
Implement the File "FILE CHANGE" RPC Locker definitions listed in the RPC section below

### RPCs
- [ ] [F191 ORWUL FV4DG](http://vistadataproject.info/artifacts/vistaRPC%20documentation/ORWUL%20FV4DG)

### Target Date
{INSERT TARGET DATE}

### Difficulty
Difficult

### [Acceptance Criteria](https://github.com/vistadataproject/nonClinicalRPCs/wiki/Software-Development:-RPC-Implementation-Workflow#acceptance-criteria)
- [ ] Locker definitions implemented and documented appropriately
- [ ] Jasmine tests with multiple input types: written and passing
- [ ] Jasmine tests that compare results between RPCRunner vs. RPCLocker: written and passing
- [ ] Code review complete/code merged to `master` branch
- [ ] Demonstrate locked RPC using CPRS/RPCServer

**Comment by sidjtd** [comment]
This RPC has some challenges associated with it. In Line 5: 

``UPDTIME=$H,^ORD(101.43,"AH","S."_DGNM)=UPDTIME``
. D FVBLD

**Comment by mfuroyama** [comment]
Thanks @sidjtd! Not only is this RPC probably mis-classified (should be a CHANGE instead of a READ, which has lower implementation priority), but there doesn't seem to be a way to set the required Fileman entries via VDM.  We may have to push this one a lot farther down the stack.

**Comment by mfuroyama** [comment]
Moved to https://github.com/vistadataproject/nonClinicalRPCs/issues/155
